export const ERROR_API_MESSAGE: any = {
  1: 'Thành công',
  2: 'Unauthorized',
  3: 'An issue is occurring, please contact the administrator',
  4: 'Dữ liệu không tồn tại',
  5: 'Tên đăng nhập đã tồn tại',
  6: 'Số điện thoại đã tồn tại',
  7: 'Email đã tồn tại',
  8: 'Mật khẩu không chính xác',
  9: 'Xoá không thành công',
  10: 'Đã hoạt động',
  11: 'This account is already registered',
  12: 'Token không chính xác',
  13: 'Token hết hạn',
  14: 'Dữ liệu đã tồn tại',
  15: 'Code đã tồn tại',
  16: 'Alias đã tồn tại',
  17: 'Dữ liệu đang được sử dụng không thể xoá',
  19: 'Dữ liệu đang được sử dụng không thể xoá',
  21: 'Cần kích hoạt đơn vị giá',
  BadCredentials: 'Mật khẩu không chính xác.',
  AccountNotExist: 'Tài khoản không tồn tại.',
  ChangePasswordFailed: 'Mật khẩu hiện tại không đúng',
  ProductCodeExist: 'Mã sản phẩm đã tồn tại',
  PhoneNumberExist: 'Số điện thoại đã được sử dụng rồi.',
  EmailTemplateExist: 'Loại email đã được sử dụng rồi.',
  EmailOrPasswordFail: 'Sai tên đăng nhập hoặc mật khẩu. Vui lòng kiểm tra lại.',
  EmailNotExist: 'Email không tồn tại, vui lòng thử lại sau.',
  EmailExist: 'Email đã được sử dụng rồi.',
  UserStatusInactive: 'Tài khoản đang bị khóa. Vui lòng liên hệ với quản trị viên hệ thống để được hỗ trợ.',
  EmailTemplateNotExist: 'Email template không tồn tại, vui lòng thử lại sau.',
  ArticleRequiredFieldNotEmpty: 'Gửi duyệt vui lòng điền đầy đủ các thông tin bắt buộc.',
  RoleExist: 'Tên vai trò đã tồn tại.',
  TicketInvalid: 'Link đổi mật khẩu đã hết hạn',
  ArticlePublishAtPast: 'Ngày xuất bản phải lớn hơn ngày hiện tại.',
  NotHavePermission: 'Tài khoản không có quyền truy cập.'
};

export const ERROR_MESSAGE = {
  fieldRequired: 'This is a required field.',
  regExpEmail: 'Incorrect email format. Correct format: xxx@xxx',
  maxFileSizeExceed: 'Photos must not exceed',
  maxFileSizeExcel: 'Maximum file size must not be exceeded',
  wrongFormat: 'Please upload formats',
  wrongFormatFile: 'Only accept files with the format',
  passWordNotMatch: 'Confirm new password does not match new password.',
  regPhoneNumber: 'Phone number is in wrong format.',
  pleaseEnterNumber: 'Please enter number.',
  passwordMustBeCharacters: 'Password must contain a maximum of 6 characters.',
  regexVietNamese: 'Do not enter Vietnamese with accents.',
  pleaseTryAgain: 'Please try again.',
  errorFileUpload: 'File upload failed. Please contact the Administrator.',
  noValidPhotos: 'There are no valid photos',
  duplicateValue: 'Index number or option name must be unique within one menu. Please check!!',
  duplicatePhonenumber: 'Phone number already exists. Please check!!',
  invalidDate: 'Date format is not correct',
  DateInTheFuture: 'Date of birth cannot be in the future',
  genderIsRequired: 'Gender is required',
  genderIsInValid: 'Gender must be male, female, or other',
  statusIsInValid: 'status must be active, inActive',
  statusIsRequired: 'Status is required',
};

export const MESSAGES_SUCCESS = {
  notification: 'Notification',
  updateSuccess: 'Updated successfully',
  createSuccess: 'Add successfully',
  replySuccess: 'Reply feedback successfully',
  deleteSuccess: 'Deleted successfully',
  activeSuccess: 'Active successfully',
  inactiveSuccess: 'Inactive successfully',
  resetPasswordSuccess: 'Reset password successfully',
  exportSuccess: 'Export successfully'
};
